services:
  app:
    build: .
    ports:
      - "8080:8080"
      - "443:443"
    env_file:
      - .env
    environment:
      - SPRING_PROFILES_ACTIVE=local
      - UPLOAD_DIRECTORY=/app/uploads
    volumes:
      - ./data:/app/data
      - ./uploads:/app/uploads
