server:
  port: 443
  ssl:
    enabled: true
    key-store: /etc/letsencrypt/live/shmessenger.chxei.xyz/keystore.p12
    key-store-password: shmessenger
    key-store-type: PKCS12
    key-alias: shmessenger
