
# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle
on:
  push:
    branches: [ development ]
    tags:
      - '*'
  pull_request:
    branches: [ development ]
    tags:
      - '*'

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew publish
      - name: release
        run: |
          ls -la .github
          #         uses: ncipollo/release-action@v1.8.8
          #         with:
          #           artifacts: "build/libs/shmessenger-0.0.1-SNAPSHOT-plain.jar"
          #           bodyFile: "build/libs/shmessenger-0.0.1-SNAPSHOT-plain.jar"
          #           token: ${{ secrets.GITHUB_TOKEN }}

      - name: "publish"
        uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "latest"
          prerelease: true
          title: "Development Build"
          files: .github/build/shmessenger.jar
