# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  push:
    branches: [ development ]
  pull_request:
    branches: [ development ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Set up JDK 16
        uses: actions/setup-java@v2.2.0
        with:
          java-version: '16'
          distribution: 'adopt'
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew bootJar
      - name : publish
        uses: ncipollo/release-action@v1.8.8
        with:
          artifacts: "./build/libs/shmessenger-0.0.1-SNAPSHOT-plain.jar"
          bodyFile: "./build/libs/shmessenger-0.0.1-SNAPSHOT-plain.jar"
          token: ${{ secrets.GITHUB_TOKEN }}
        
  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: ncipollo/release-action@v1
      with:
        artifacts: "./build/libs/shmessenger-0.0.1-SNAPSHOT-plain.jar"
        bodyFile: "./build/libs/shmessenger-0.0.1-SNAPSHOT-plain.jar"
        token: ${{ secrets.GITHUB_TOKEN }}
